create database Topito_DB;

create table Users (
	Id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
 	Login varchar(20) not null,
	Mail varchar(20) not null,
	Password varchar(255) not null,
	Balance int default 0
);

create table Admins (
	Id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
 	Login varchar(20) not null,
	Password varchar(255) not null

);

create table Resource_Status (
	Id int generated by default as identity (start with 1 increment by 1) primary key,
	Name varchar(20) not null
);

create table Conditions (
	Id int generated by default as identity (start with 1 increment by 1) primary key,
	Name varchar(20) not null
);

insert into Resource_Status(Name) values 
('Выставлен'),
('Продан');

insert into Conditions(Name) values
('Новый'),
('Б/У');

create table Resources (
	Id int generated by default as identity (start with 1 increment by 1) primary key,
	Owner_Id int not null references Users(Id) on delete cascade,
	Name varchar(80) not null,
	Description text,
	Price int not null,
	Condition int not null references Conditions(Id) on delete cascade,
	Status int not null references Resourse_Status(Id) on delete cascade default 1
);

create table Order_Status (
	Id int generated by default as identity (start with 1 increment by 1) primary key,
	Name varchar(20) not null
);

insert into Order_Status(Name) values 
('Ожидание'),
('Продан'),
('Отменён');

create table Orders (
	Id int generated by default as identity (start with 1 increment by 1) primary key,
	Resource_Id int not null references Resources(Id) on delete cascade,
	Customer_Id int not null references Users(Id) on delete cascade,
	Quantity int not null,
	Status int not null references Order_Status(Id) on delete cascade default 1
);

create table Feedbacks (
	Id int generated by default as identity (start with 1 increment by 1) primary key,
	Order_id int not null references Resources(Id) on delete cascade,
	Stars int not null,
	Description varchar(255)
);