create database Topito_DB;

create table Users (
	Id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
 	First_name varchar(20) not null,
	Second_name varchar(20)
);

create table Resourse_Status (
	Id int generated by default as identity (start with 1 increment by 1) primary key,
	Name varchar(20) not null
);

insert into Resourse_Status(Name) values 
('Выставлен'),
('Продан');

create table Resourses (
	Id int generated by default as identity (start with 1 increment by 1) primary key,
	Owner_Id int not null references Users(Id) on delete cascade,
	Name varchar(80) not null,
	Description text,
	Price int not null,
	Status int not null references Resourse_Status(Id) on delete cascade default 1
);

create table Order_Status (
	Id int generated by default as identity (start with 1 increment by 1) primary key,
	Name varchar(20) not null
);

insert into Order_Status(Name) values 
('Ожидание'),
('Продан'),
('Отменён');

create table Orders (
	Id int generated by default as identity (start with 1 increment by 1) primary key,
	Vendor_Id int not null references Users(Id) on delete cascade,
	Resourse_Id int not null references Resourses(Id) on delete cascade,
	Customer_Id int not null references Users(Id) on delete cascade,
	Status int not null references Order_Status(Id) on delete cascade default 1
);